---

- name: Ensure Karaf is running
  service: name=karaf state=started

- name: Install Karaf features
  command: "{{ karaf_home }}/bin/client {{ item }}"
  with_items: "{{ karaf_feature_install }}"
